### ISSUE TITLE
'Faint' appears darker than 'Grey' in the 'Light' theme

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersJS#75]
infinitesimal priority

**Comment by cqx931** [comment]
https://github.com/dhowe/ReadersJS/pull/85/commits/96d1f2ca464156cec983999858c1d62524264937 This should fix the issue.

**Comment by dhowe** [comment]
this button still doesn't work for me:

1. the options should be in order in the interface, from darker to lighter (or vice-versa)
2. the terms are still confusing: faint text is the same as dark text if the background is black. if it is light, then these are the opposite of each other (should be something like black/gray/white or light/middle/dark)

**Comment by cqx931** [comment]
For me the options are more like:
obvious
faint
vague
Then the text doesn't have to be changed when the user switch the theme.

**Comment by dhowe** [comment]
neither faint nor vague are really descriptive (that is, they are vague)

I agree that the text should not change when the theme does, but can't we just use either of the below, and just assign an alpha value to each that doesn't change?

black/gray/white 
light/middle/dark

**Comment by cqx931** [comment]
What we have now for the style is to have an alpha value assigned to each style and change accordingly.

**Comment by dhowe** [comment]
> Then the text doesn't have to be changed when the user switch the theme.

so why would we have to change the text for the options above?

**Comment by shadoof** [comment]
closing this. make separate, new issues for anything related
